tests_location = "invalid/home/fuexfollets/tests/"

[forall_presets]
copy_with = ["/home/someuser/words.txt"]
execute_in_test_directory = [["touch", "note.txt"]]

[presets.example_preset]
copy_with = ["~/some-file-in-home-directory", "./some-file-in-current-working-directory"]
execute_in_test_directory = [
    ["this", "is", "executed", "in", "the", "new", "test", "directory"],
    ["and", "so", "is", "this"]]

[presets.cpp]
copy_with = ["./lib/some-library/", "./main.cpp", "/home/some-user/standard/Makefile"]
execute_in_test_directory = [["make", "main"], ["wget", "github.com"]]

